# Generated by Django 6.0.7 on 2026-08-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='used_reward',
            field=models.BooleanField(default=False),
        ),
    ]
