# Generated by Django 6.0.7 on 2026-08-25 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchase_used_reward'),
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='redemption',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase', to='rewards.rewardredemption'),
        ),
    ]
