# Generated by Django 6.0.7 on 2026-09-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ICE_CREAM', 'Helado'), ('DRINK', 'Bebida'), ('TOPPING', 'Complemento'), ('OTHER', 'Otro')], default='ICE_CREAM', max_length=20),
        ),
    ]
