# Generated by Django 6.0.7 on 2026-07-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True, unique=True),
        ),
    ]
