# Generated by Django 6.0.7 on 2026-07-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_populate_customer_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
