# Generated by Django 6.0.7 on 2026-09-17 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category'),
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='free_product_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='reward',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rewards', to='products.product'),
        ),
        migrations.AddField(
            model_name='reward',
            name='reward_type',
            field=models.CharField(choices=[('FREE_PRODUCT', 'Producto gratis'), ('PERCENTAGE_DISCOUNT', 'Descuento porcentual'), ('FIXED_DISCOUNT', 'Descuento fijo')], default='FREE_PRODUCT', max_length=30),
        ),
    ]
